week1assesment-lc
learn-academy-2022-delta/week-1-assessment-LeoContreras93 pull request #1
Opened 2022-06-21 16:48 UTC by LeoContreras93

# Submitting Week 1 Assessment

### ✅ Completed Files
Select the following as confirmation that the files in this repository are complete.
- [x] Coding Challenges
- [x] Coding Concepts
- [x] Interview Questions

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:
### I struggled with question #4 on coding challenges. the code would readout odd/even but for all numbers. not sure if i missed something or  was invoking the wrong one in console log.
### I also struggled with understanding question #4 and why the built in method didn't necessarily work?

2022-06-22 23:02 UTC, elysemontano requested changes
Changes requested: All researched answers must be formed **in your own words**. No copying and pasting from any resources. I want to know your understanding of the concept, not googles. I will approve when your interview answers are updated.

2022-06-22 23:02 UTC, elysemontano commented on code-challenges.js
> +// Pseudo code: so any of the 3 test variables i place in console will return an answer about the tempature being below,at or above boiling point. tempature is my special veriable and I am invoking t
I would really like to see your pseudocode display the thought process of the logic you have written below.

2022-06-22 23:02 UTC, elysemontano commented on code-challenges.js
> +// Pseudo code: unable to get the result of odd even, tried creating global variable with odd and even
I appreciate that you are mentioning what you are struggling with, but I need to see pseudocode that reflects the current logic shown below.  That being said, how are you accessing the current value in your array inside the for loop?  Also, double-check your statement on line 89.

2022-06-22 23:02 UTC, elysemontano commented on code-challenges.js
> +// Pseudo code: I am not sure how to set this up where i put in 58-100 to show 42 and vice versa
Same thing as I mentioned above, I need to see your pseudocode here, how did you break down the problem to get the result currently?

2022-06-22 23:02 UTC, elysemontano commented on coding-concepts.js
> +// b) Verify and explain: an error occur with the built in method stating it is not a function, the other reason i think it wont work also is the strings are built into an array??
.toUpperCase() is a built-in method that only works on strings

2022-06-22 23:02 UTC, elysemontano commented on interview-questions.md
> +  Researched answer: Simply put, Git is a version control system that lets you manage and keep track of your source code history. GitHub is a cloud-based hosting service that lets you manage Git repo
Researched answers must be formed **in your own words**.

2022-06-22 23:02 UTC, elysemontano commented on interview-questions.md
> +  Your answer: Equality Operators, there are three types, loose equality, strict equality and logical operator
One-line answers are meeting the bare minimum requirement for this section and will come off as uninterested to an employer in an interview.  I would highly recommend expanding and discussing what each one does.

2022-06-24 16:19 UTC, LeoContreras93 commented
changes made to week 1 assesment

2022-06-24 16:38 UTC, elysemontano approved these changes
Great job on the updates!  Approved!

2022-06-24 16:53 UTC, merged